const throwError = () => {
  throw new Error(MESSAGE.EXCEPTION_QUIT);
};

module.exports = throwError;
